// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music.Models;

namespace Music.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20220608220147_SeedMoreData")]
    partial class SeedMoreData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Music.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArtistName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            ArtistName = "NOFX",
                            Genre = "Punk",
                            YearFounded = 1990
                        },
                        new
                        {
                            ArtistId = 2,
                            ArtistName = "Tupac Shakur",
                            Genre = "Hip Hop",
                            YearFounded = 1989
                        },
                        new
                        {
                            ArtistId = 3,
                            ArtistName = "Phil Ochs",
                            Genre = "Folk",
                            YearFounded = 1962
                        },
                        new
                        {
                            ArtistId = 4,
                            ArtistName = "The Coup",
                            Genre = "Hip Hop",
                            YearFounded = 1991
                        },
                        new
                        {
                            ArtistId = 5,
                            ArtistName = "Refused",
                            Genre = "Punk",
                            YearFounded = 1991
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
